<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PictureDirectory</RootNamespace>
    <AssemblyName>PictureDirectory</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Authors>Ezequiel Fernández Ponce</Authors>
    <Product>PictureDirectory</Product>
    <Description>Sorts photos and videos into date-named folders based on EXIF metadata, filename conventions, or file timestamps.</Description>
    <Copyright>Copyright © 2018-2026</Copyright>
    <Version>1.0.0</Version>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
  </ItemGroup>

</Project>
